In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns = ['cgpa','p_score','lpa'])

In [3]:
df

cgpa  p_score  lpa
0     8        8    4
1     7        9    5
2     6       10    6
3     5       12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

Now Keras model randomly assigns the Intial weights and biases but to match it from our own inital weights and biases W = 0.1 and B = 0.0 we update them manually

In [7]:
model.get_weights()

[array([[-0.76063645, -1.2106302 ],
        [ 0.83701885, -0.70935595]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.6851307 ],
        [0.10335076]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype = np.float32),
               np.array([0., 0.], dtype = np.float32),
               np.array([[0.1], [0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values, epochs= 75, verbose = 1, batch_size = 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 29.5718
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.1311 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.0246 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30.7570 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21.5128
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.7861 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4184 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.3264
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30.0760
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.6244
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20.9862 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.6579
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.1144
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.9485
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.3661
Epoch 16/75
4/4 ━━

optimizer adam use hua probably issliye convergence ke liye 85 epoch lage

In [13]:
model.get_weights()

[array([[0.37392583, 0.37392583],
        [0.36579353, 0.36579353]], dtype=float32),
 array([0.2725562, 0.2725562], dtype=float32),
 array([[0.37315613],
        [0.37315613]], dtype=float32),
 array([0.20486341], dtype=float32)]